# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_den_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout',
            name='den',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouts', to='awards.Den'),
        ),
    ]
